-- 001_initial_schema.sql (V2 - Safe Backup Mode)

-- 1. Backup Legacy Tables (Prevent Type Conflicts)
-- We check if they exist and are using the old schema (inferred by existence)
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'hospitals') THEN
        ALTER TABLE public.hospitals RENAME TO hospitals_legacy;
    END IF;
    
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'ambulances') THEN
        ALTER TABLE public.ambulances RENAME TO ambulances_legacy;
    END IF;

    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'incidents') THEN
        ALTER TABLE public.incidents RENAME TO incidents_legacy;
    END IF;
END $$;

-- 2. Continue with V2 Schema Creation
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2.1 Types
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'dispatcher', 'ambulance', 'hospital');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE incident_status AS ENUM ('pending', 'assigned', 'picked_up', 'resolved', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE ambulance_status AS ENUM ('idle', 'busy', 'offline');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2.2 Tables
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT NOT NULL,
  role user_role DEFAULT 'ambulance',
  full_name TEXT,
  phone_number TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hospitals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL, 
  address TEXT,
  resources JSONB DEFAULT '{"beds": 0, "oxygen": 0, "blood": {}}',
  admin_id UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ambulances (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  driver_id UUID REFERENCES public.profiles(id),
  plate_number TEXT UNIQUE NOT NULL,
  status ambulance_status DEFAULT 'offline',
  current_location GEOGRAPHY(POINT),
  home_hospital_id UUID NOT NULL REFERENCES public.hospitals(id), -- Strict Hierarchy
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.incidents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status incident_status DEFAULT 'pending',
  location GEOGRAPHY(POINT) NOT NULL,
  address TEXT,
  reported_by UUID REFERENCES auth.users(id),
  assigned_ambulance_id UUID REFERENCES public.ambulances(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ambulances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refresh_tokens ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Re-create logic)
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
CREATE POLICY "Users can read own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Public read hospitals" ON public.hospitals;
CREATE POLICY "Public read hospitals" ON public.hospitals FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins update hospitals" ON public.hospitals;
CREATE POLICY "Admins update hospitals" ON public.hospitals FOR UPDATE USING (auth.uid() = admin_id);

DROP POLICY IF EXISTS "Auth users view ambulances" ON public.ambulances;
CREATE POLICY "Auth users view ambulances" ON public.ambulances FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Drivers update own ambulance" ON public.ambulances;
CREATE POLICY "Drivers update own ambulance" ON public.ambulances FOR UPDATE USING (auth.uid() = driver_id);

DROP POLICY IF EXISTS "Public reporting" ON public.incidents;
CREATE POLICY "Public reporting" ON public.incidents FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Auth view incidents" ON public.incidents;
CREATE POLICY "Auth view incidents" ON public.incidents FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Update assigned incident" ON public.incidents;
CREATE POLICY "Update assigned incident" ON public.incidents FOR UPDATE USING (
  auth.uid() IN (
    SELECT driver_id FROM public.ambulances WHERE id = assigned_ambulance_id
  ) OR 
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'dispatcher'))
);

-- 5. Indexes
CREATE INDEX IF NOT EXISTS hospitals_geo_idx ON public.hospitals USING GIST (location);
CREATE INDEX IF NOT EXISTS ambulances_geo_idx ON public.ambulances USING GIST (current_location);
CREATE INDEX IF NOT EXISTS incidents_geo_idx ON public.incidents USING GIST (location);

-- 6. Realtime
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.incidents;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.ambulances;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
